---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.k3s.io/name: homeassistant
  name: home-assistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.k3s.io/name: homeassistant
  name: homeassistant-pvc
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: home-assistant
spec:
  ports:
    - name: "8123"
      port: 8123
      protocol: TCP
  selector:
    app.k3s.io/name: homeassistant
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.k3s.io/name: homeassistant
  name: homeassistant
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.k3s.io/name: homeassistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.k3s.io/name: homeassistant
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{ "name" : "macvlan-dhcp-ha", "mac": "8a:8a:b5:ce:04:33" }]'
    spec:
      containers:
        - image: ghcr.io/home-assistant/home-assistant:stable
          imagePullPolicy: Always
          name: homeassistant
          ports:
            - containerPort: 8123
              protocol: TCP
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - mountPath: /etc/localtime
              name: tz-config
              readOnly: true
            - mountPath: /config
              name: ha-data-volume
      restartPolicy: Always
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/Chicago
        - name: ha-data-volume
          persistentVolumeClaim:
            claimName: homeassistant-pvc
        
