apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  labels:
    app.k3s.io/name: mosquitto
data:
  mosquitto.conf: |

    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
    
    # MQTTS listener, I did not add WebSocket one as unneeded right now
    listener 8883
    protocol mqtt
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  labels:
    app.k3s.io/name: mosquitto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtts
  labels:
    app.k3s.io/name: mosquitto
spec:
  type: NodePort
  selector:
    app.k3s.io/name: mosquitto
  ports:
  - port: 8883
    nodePort: 30883
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app.k3s.io/name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app.k3s.io/name: mosquitto
  template:
    metadata:
      labels:
        app.k3s.io/name: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
          - containerPort: 8883
        volumeMounts:
          - mountPath: /etc/mosquitto/
            name: config
          - mountPath: /mosquitto/data/
            name: data
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data
