---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
  namespace: home-assistant 
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "vlan3@eno1",
      "ipam": {
        "type": "static",
        "routes": [
          { "dst": "10.1.3.0/24", "gw": "10.1.3.1" }
        ]
      }
    }

